from typing import Protocol


class KeyboardDevice(Protocol):
    async def press(self, key: str, count: int, interval: float) -> None: ...
    async def hotkey(self, keys: tuple[str, ...]) -> None: ...
    async def write(self, text: str, interval: float) -> None: ...
