from typing import Protocol


class MouseDevice(Protocol):
    async def click(self, **kwargs: object) -> None: ...
    async def move(self, **kwargs: object) -> None: ...
    async def scroll(self, **kwargs: object) -> None: ...
