from typing import Any, Protocol


class WindowQuery(Protocol):
    def query(self, title: str) -> dict[str, Any]: ...


class WindowController(Protocol):
    async def activate(self, title: str) -> None: ...
    async def minimize(self, title: str) -> None: ...
    async def restore(self, title: str) -> None: ...
    async def move_resize(self, title: str, geometry: tuple[int, int, int, int]) -> None: ...
